### PR TITLE
Added Iceologer

### PR DESCRIPTION
**Pull request by Ocelot5836**
**This PR adds:**
- Iceologer entity
- Ice Cloud entity
- Ice Chunk entity
- Ice Wand item
- Iceologer Spawn Egg item
- Frozen effect

### CODE REVIEW

**Comment by bageldotjpg** [comment]
Ok, initial thoughts

- Ice Wand ideally could have a range limit, it seems to be near-infinite right now?

- Right clicking a block with an Ice Wand should put an Ice Chunk above that block

- Ice Wand should have a cooldown so you can't just spam on a mob. Maybe compensate with a bit more damage.

Will continue testing

**Comment by bageldotjpg** [comment]
There's not much to look at since most of its pretty straightforward, just have a bit of Ice Wand critique. We'll be doing some changes of our own obviously to expand the content a bit more so I really just have thoughts on the Ice Wand.

**Comment by bageldotjpg** [comment]
The Ice Cloud attack is really cool, good job with that.

**Comment by bageldotjpg** [comment]
Another thing discussed

- "Frostburn" effect

- Replaces and combines the Wither / Frozen effects given

- Slightly weaker than Wither's damage, frozen in place during effect

- Jackson mentioned a Frozen Heart visual? That would be ideal for this as well

**Comment by Ocelot5836** [comment]
> * Ice Wand ideally could have a range limit, it seems to be near-infinite right now?

Ice wand range is 16 blocks. I made a mistake so it was 256

> * Ice Wand should have a cooldown so you can't just spam on a mob. Maybe compensate with a bit more damage.

A cooldown wouldn't matter because entities have their own damage cooldown. Spamming the item just wastes durability and multiple will still fall at the same time anyways.

**Comment by Farcr** [comment]
I have some feedback to put:
-Ice chunks not linked to a mob should still float for a while.
-The Ice Wand cooldown should be 5 seconds
-When trying to spawn an Ice Chunk out of range, snowflake particles should appear near the Ice Wand, signaling that it didn't work.



And now, let me just add a comment: ALL OF THIS IS PHENOMENAL. You did an incredibly good job, WAAAAY better than anyone expected! Thank you so much man, your contribution will be appreciated

**Comment by bageldotjpg** [comment]
Ok, I'm merging because this is a good start and even if incomplete I have some more stuff to do on S&R. 
Leaving a to-do list for later.

Ice Wand

- Ice Chunks summoned on blocks should still float for some time

- (If possible) Ice Chunk becomes solid like Shulkers potentially making them usable for parkour

- (If possible) Ice Chunk does AoE damage, causing damage to every entity it collides with when ithits the ground

- (If possible) Ice Wand should raytrace through non-solid blocks like tall grass

Frostbite Effect

- Deals damage like Wither effect, a bit slower

- Turns your hearts icy blue

- Being on fire removes the effect

- Slows your movement

**Pull request merged**
